## 自动求导

In [11]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

储存梯度

In [12]:
x.requires_grad_(True)
x.grad # 默认为None

In [13]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [14]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
x.grad == 4 * x

tensor([True, True, True, True])

In [16]:
# 在默认情况下,PyTorch会累积梯度,我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

对非标量调用`backward`需要传入一个`gradient`参数

In [17]:
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [19]:
x.grad.zero_()
y = x * x
u = y.detach()  # 把y当成常数
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [20]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

即使构建函数的计算图需要通过Python控制流,我们仍然可以计算得到变量的梯度

In [22]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size = (), requires_grad = True)
d = f(a)
d.backward()

a.grad == d/a

tensor(True)

## 线性回归